// <auto-generated />
namespace nTestSwarm.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddJobCorrelation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddJobCorrelation));
        
        string IMigrationMetadata.Id
        {
            get { return "201302072119451_AddJobCorrelation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
