// <auto-generated />
namespace nTestSwarm.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Program : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Program));
        
        string IMigrationMetadata.Id
        {
            get { return "201301301601350_Program"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
